### ISSUE TITLE
Code changes to make on indicators graphic

### ISSUE THREAD

**Issue by kshotwell** [kshotwell/AKesp#1]
From discussion on 3/9/2022: 
Updates to indicator graphic: 
1.) remove green rectangle 
2.) change high/low on figure to a symbol 
3.) change to +- SD lines, not quantiles 
4.) add units somewhere (source from lookup table on AKFIN)

**Comment by atyrell3** [comment]
Fixed #1-3, waiting on "units" column for #4!

**Comment by kshotwell** [comment]
Updated units column with data for BS snow crab indicators so should show up now

**Comment by atyrell3** [comment]
Added units 5/5
