### ISSUE TITLE
Parameters in rmd call

### ISSUE THREAD

**Issue by kshotwell** [kshotwell/AKesp#4]
The abbreviation parameters does not seem to be working. Thoughts?

**Comment by atyrell3** [comment]
I am working on this... it's more complicated than I thought. Issues with the variables being passed from `render_esp` to `rmarkdown::render`

**Comment by atyrell3** [comment]
It should be fixed now! Let me know if not
commit: fa101454a4bd6042205bcb0d5dbe87653e0d23ca
