### ISSUE TITLE
out of order indicators?

### ISSUE THREAD

**Issue by kshotwell** [kshotwell/AKesp#8]
for some reason a couple of the indicators are not going into the graphics in the correct order (e.g., pH in bristol bay red king report card, see attached). Any thoughts as to why? 
[bbrkc_2022_rc.docx](https://github.com/kshotwell/AKesp/files/9460622/bbrkc_2022_rc.docx)

**Comment by atyrell3** [comment]
Answered over email -- need to make sure to update the indicator order key ([script here](https://github.com/kshotwell/AKesp/blob/main/data-raw/esp_lookup.R)), also make sure no indicators have duplicate names.
