### ISSUE TITLE
Indicator not responding to indicator_order field

### ISSUE THREAD

**Issue by kshotwell** [kshotwell/AKesp#9]
Cannot figure out what's happening with the cold pool indicator for snow crab ESP. Everything maps accordingly except that one. It keeps wanting to go at the end of the list in the graphics output. The ESP_Lookup_Order seems correct. There's only this weird upside down ? in the report card title, but I tried to delete that and it won't link up. Confusing. Any thoughts here?

**Comment by atyrell3** [comment]
I'll take a look at this today and see what I can figure out.

**Comment by kshotwell** [comment]
Actually I figured it out yesterday, it was an inconsistency between the lookup table we have in the r package and the metadata table we have in the data management tool on akfin. I fixed it and now everything goes in the right order. Probably not a good idea to have two tables to maintain like this, so I'm chatting with akfin today about this. will add more after we discuss options. Thanks for looking!
